#+STARTUP: showall
#+TITLE: Program: Very Simple Simulated Disk (vssd++)
#+SUBTITLE: CIS 310: Operating Systems
#+LANGUAGE: C++
#+AUTHOR: Brian C. Ladd
#+DATE: Fall 2018
#+OPTIONS: toc:nil H:1 num:0
#+INCLUDE: ../default_packages.org

* Acknowledgment
The VSSD++ and VSFS++ assignments were inspired by Rice University's various Valnix disk and file system assignments that can be found on the Web. They also draw from the peripheral and file system descriptions in OSTEP.

* Overview
Students will implement Very Simple Simulated Disks, vssd, to gain some facility with the abstract interface of a disk and, by implementing two different kinds of disks, how that abstract interface smooths over differences in the underlying "hardware". This is exactly the purpose of driver code in an operating system: uniform presentation of heterogeneous hardware to the next higher layer of abstraction.

The vssd are block-based storage, effectively persistent arrays of blocks. Note that "sector" and "block" are synonymous in this and following assignment. Block contents are /opaque/ to the vssd; the vssd treats them as uninterpreted sequences of bytes (with one exception described below).

One of the major challenges of operating system design is the problem of dealing with different types of hardware devices while providing a convenient programming interface for controlling them. In this assignment, students explore this problem by looking at supporting "physical" and "RAM" disks.

* The Abstract Programming Interface (API)
** The Public Interface
An API is the publicly exposed interface of a library or subsystem.
*** Consider =List= in Java.
The client code, that /using/ the =List= interface, need not know anything about the internal representation of a =LinkedList= or an =ArrayList=. The =List= provides a common interface for the client and the implementation can change according to need without client code needing rewriting.
*** API controls complexity through abstraction.
As the name indicates, the *Abstract* Programming Interface uses abstraction to separate the programmer's task into two layers: one is /implementing/ the API atop a particular implementation; the other is /using/ an instance of the API. So long as the contract is well understood, a programmer can focus on one side with little intellectual overhead devoted to the other side of the divide.

** The *Facade Pattern*
An API is often an example of the facade *design pattern*.
*** Design Pattern?
A *[[https://www.tutorialspoint.com/design_pattern/design_pattern_overview.htm][design pattern]]* is a named relationship between one or more classes in an object-oriented program. The naming comes after a programmer sees the same relationship recurring in multiple programs. Taken together, design patterns form a "pattern language" for talking about entities and their /relationships/ within a program at a level of abstraction above that provided by any given programming language.

The *[[https://www.tutorialspoint.com/design_pattern/facade_pattern.htm][facade pattern]]* (analogous to a building's facade) is a pattern where an object provides a fixed interface to smooth over differences in multiple underlying subsystems. The facade is the interface and a particular backend can be used through the facade after a driver/translator is implemented and wrapped around the subsystem, hiding the specific complexities. One hard part of designing a facade is extracting the minimal functionality that defines *all* of the subsystems that will be brought into it.

*** vssd++
vssd++ (the C++ evolution of the vssd assignment) uses a simple abstract base class to provide the facade over two different types of disk drives. One test harness, written to the API, can test multiple implementations of a simulated disk.

* vssd++: The Interface
As you are hopefully aware, disk drives come a wide variety of flavors---hard disks, floppy disks, zip disks, CD-ROMS, DVDs, and solid-state drives. At the lowest level, all disk drives are "block devices." That is, the devices only know how to operate on blocks of data that are typically between 512 and 4096 bytes in size. Disks really only have two primary functions:

#+begin_src c++
    VVSSD::read(unsigned int blocknum, void *buffer)
    VVSSD::write(unsigned int blocknum, void *buffer)
#+end_src

Each member function is called on the disk that it is to operate on. Each takes a physical block number on which to operate and a pointer into memory for a block's worth of data; if the disk is not obvious, consider what =this= represents. =read= retrieves the designated block of data from the disk and copies it into the buffer. =write=  takes the data that's stored in the buffer and copies it in the designated disk sector.

Although disks are easy to describe /at a high-level/, supporting them /in detail/ is tricky. As mentioned, a wide variety of disk devices could be attached to a system. Moreover, there are a lot of other things that behave somewhat like disks, but which aren't (disk images, RAM disks, network storage devices, etc.). Implementing an established API is an exercise in papering over these differences.

** The Interface
The interface for a vssd++ is represented in the abstract class =VVSSD= (Virtual Very Simple Simulated Disk). An /abstract class/ is similar to the Java =interface= (or =abstract= keyword) in that it can provide a set of member function declarations that can be programmed against (the client code uses the interface) and *must* be implemented by classes extending the abstract class.

 #+BEGIN_SRC c++ file: VVSSD.h
   class VVSSD {
    public:
     virtual std::size_t blockSize() const = 0;
     virtual std::size_t blockCount() const = 0;
     virtual DiskStatus status() const = 0;
     virtual DiskStatus read(blocknumber_t block, void * buffer) = 0;
     virtual DiskStatus write(blocknumber_t block, void * buffer) = 0;
     virtual DiskStatus sync() = 0;
   };
 #+END_SRC

*** C++ Translations
**** =DiskStatus= is an enumerated type for specifying the outcome of disk operations. It includes values such as =OK=, =NOT_READY=, and =NOT_YET_IMPLEMENTED=.
**** =virtual= methods are like all Java member functions: the lowest definition of the function for the *actual* type is called, regardless of the *apparent* type. Assume =FileVSSD= extends =VVSSD=, defining all the interface methods. Then
 #+BEGIN_SRC c++
   VVSSD * disk = new FileVSSD(...the parameters that work...);
   disk->sync();
 #+END_SRC
   calls =FileVSSD::sync=, not the non-existent =VVSSD::sync=.
***** (You can assume that leaving =virtual= off the declaration does something different. It causes the call to be resolved based on the *apparent* rather than the actual type. See you in /Programming Languages/ for a discussion of how that might work.)
**** =const= after the parameter list of a member function indicates that the member function is safe to call on a =const= object of the class. Colloquially it mean the function does not change any fields of the object (as with much of C++, it is more omplicated than that blanket statement but we do not care).
**** And the final = = 0; = at the end of the line. That says there is no function definition for the declared function. That is, if a declaration of a function ending with just the semicolon is a promise to the compiler that there /is/ a definition somewhere and it can be found at link time and extending classes will inherit it if they do not supply their own, the equals zero can be read as requiring extending classes provide their own definition.
*** Semantics
**** The first three functions are informational: they return the /geometry/ of the disk in terms of the number and size (in bytes) of the disk and the status of the last call to an API function. These three functions are =const= because they only read data from the disk and return it to the caller.
**** The =read= and =write= methods are the core of the interface: they read a block from and write a block to the underlying disk. They return a =DiskStatus= value to let the caller know whether or not it worked.
**** =sync= flushes any buffered writes out to the disk. It is most likely just a NOP since this assignment says nothing about buffering of data.

* The Disk Drives
  This project requires you to implement two different disk drives, one purely in memory (and therefore not actually persistent across multiple connections) and the other inside a disk file. The test code, programmed against the =VVSSD= interface, is agnostic as to what kind of disk is in use at any given moment. Only when connecting to a disk to use it does it matter as the correct constructor must be called.

** The Constructors
  To keep the new code from being overwhelming, the test framework has (commented out when you get it) calls to the constructors for the two types of disks you are implementing. Each takes four parameters:
  - =block_size= the size in bytes of the disk; must be greater than or equal to 32
  - =block_count= the number of blocks on the disk; must be greater than or equal to 2
  - =filename= the name of the file; can be empty for disks that do not use one
  - =truncate= a Boolean indicating whether the disk representation should be reinitialized for those disks where this is a choice; defaults to false

  To use the given constructor, just by uncommenting it, include all four parameters in the disk's constructor. Alternatively, remove the parameters that the disk does not need when uncommenting. C++ supports several ways to build factory methods that are more automatic than the hand-build one used in the test code. The automation comes at the price of using very sophisticated language constructs, a price beginning C++ programmers should not have to pay.

** Sector Zero
  Block 0 is special: it is an error to read or write to it through the read or write methods in the interface. That block is free for the disk itself to use. Suggested uses: the first two unsigned int sized blocks should store the geometry of the disk so that when reopening a persistent disk, you can check that the geometry matches that given. You could even imagine a constructor that did not need the geometry and could automatically open any disk properly. After the geometry there might be a signature, a sequence of bytes that lets the opening program verify that the file being opened was written by a compatible version of the  program.

Note that Sector Zero is the reason for the geometry limitations in the previous section: 32 bytes so two integers and a signature can fit; at least 2 sectors so at least 1 is available to the user.

** RAMVSSD
   The RAM disk, =RAMVSSD= creates a memory buffer the size of the disk drive it is created with. Since the data is in memory, when the disk is disconnected, the data goes away. The RAM disk is non-persistent.

  Note that you *must* either call =delete[]= to release a raw pointer or make use of the new =unique_ptr<>= template that can call it for you. Using a raw pointer is lower level and perfectly acceptable in this class; the other approach is an attempt to make C++ memory management easier.

** FileVSSD
  A file disk, =FileVSSD=, also known as a /disk image/, is a file that is treated (by your disk drive class) as a block-addressable data store. The file underlying the =FileVSSD= *is* persistent. This means that the disk can be disconnected (or a program using it can terminate) and the data in the various sectors will remain where it was the next time it is connected.

Further, this means there are actually two different operations when constructing a =FileVSSD=: open and initialize it so all user-addressable blocks are filled with zero bytes or open an already existing disk image. When opening an existing image, use the contents of Sector Zero to confirm the geometry and authenticity of the image.


* Getting Started
** In the class code repository there is a new directory, =pVSSD=. It has the same multi-module structure of our programs. Copy it into a directory with a clean git database and =make= it. It will give lots of errors when you test the included device but it will compile.
*** Your new files should go in =src/vssd-solution=, along side the =UnImplVSSD= files.

* Challenges - What you *can* and /*cannot*/ do
  You are implementing the =RAMVSSD= and =FileVSSD= devices.
** Put the device files (=.h=/=.cpp=) in the =src/vssd-solution= folder.
** Each of your device classes *must* inherit from (Java: =extend=) =VVSSD=. That means the name of the class must be followed by a colon and the name of the parent class.
** When you are done, there will be 4 devices in the program:
   - =VVSSD= the interface device; cannot be instantiated
     - =UnImplVSSD= a dummy device that lets the code you get compile; all methods return =NOT_YET_IMPLEMENTED=.
     - =RAMVSSD= the RAM disk device
     - =FileVSSD= the disk image device
** If any file includes the =.h= file for a device, that file /refers/ to the given device.
*** No device extending =VVSSD= can refer to any device other than its parent device.
** You may modify =main/main.cpp= in order to permit instantiation of the new devices.
** You may modify =vssd/DiskStatus.*= if you find more errors useful. Make sure to add the new errors to the two translation functions in the =.cpp= file.
** =vssd/VVSSD.h= *MUST NOT* change.

* Advise/Approach
** The /implementation/ of a device is exactly the implementation of a class extending our interface class.
*** After implementation, the device must be uncommented in =main.cpp=.
** The =RAMVSSD= and =FileVSSD= classes will be almost identical in their declaration with the same abstract methods overridden and very similar constructors. The definition of the methods will differ.
** The C++ used
*** =RAMVSSD= needs mainly  =new=, =delete[]= and =std::memcpy=.
*** =FileVSSD= uses the =fstream= interface with =seekg/p=, =read=, =write=, and opening and closing.
* Deliverables/Submission Method
** Submission is through =git=
** The project is to be developed in a project directory structured as in the =cppProjectTemplate=
*** Name the directories under =src/= according to your choice of names for modules in the project
*** Make sure there is one executables module using the =executables.mk= Makefil file
*** Copy (recursively) the =src/module/= directory to start new modules as necessary
**** You need to make sure the names of all modules are in =src/allModule.=
**** The recursive copy gets the module version of =module.mk= into the directory

** The base directory of the project is to be a =git= repository
*** Make sure it has an appropriate C++ (and your editor) =.gitignore= file.
*** Make sure to *delete* the =.git= folder (the whole history of the template) *and* run =git init= to create a new history

** Log in to =GitTea= at [[https://cs-devel.potsdam.edu]]
*** Create a new, empty repository on =cs-devel=.
**** The name *must* begin with  =p001=.
**** The name of the repository of /each/ program you turn in will begin with =p###= where "###" is the number of the assignment.
*** After the =GitTea= will guide you to connect your /local/ repository (where your solution lives) to the /remote/ repository.
**** Notice that the instructions differ on when you create the new repository on =cs-devel=.

** Submit using git to push to git@cs-devel.potsdam.edu in the repo you made.
